package com.decisioncustom.mapper;

import com.decisioncustom.query.BaseQuery;

import java.io.Serializable;
import java.util.List;

public interface CrudMapper<T>{
        List<T> getDataByQuery(BaseQuery query);

        int getCountByQuery(BaseQuery query);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table mst_administrator
         *
         * @mbggenerated
         */
        int deleteByPrimaryKey(Serializable id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table mst_administrator
         *
         * @mbggenerated
         */
        int insert(T record);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table mst_administrator
         *
         * @mbggenerated
         */
        int insertSelective(T record);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table mst_administrator
         *
         * @mbggenerated
         */
        T selectByPrimaryKey(Serializable id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table mst_administrator
         *
         * @mbggenerated
         */
        int updateByPrimaryKeySelective(T record);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table mst_administrator
         *
         * @mbggenerated
         */
        int updateByPrimaryKey(T record);

        List<T> selectAll();
}
