package com.decisioncustom.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Employee {
    //部门
    private Department department;
    //角色
    private List<Role> roles = new ArrayList<>();

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }

    private  String newPassword;

    public Employee() {
        super();
    }
    public Employee(String username, String realname, String password, Integer tel, String email, Date inputTime,
                    Integer state) {
        super();
        this.username = username;
        this.realname = realname;
        this.password = password;
        this.tel = tel;
        this.email = email;
        this.inputTime = inputTime;
        this.state = state;
    }
    private  String employeeDetails;

    @Override
    public String toString() {
        return "Employee{" +
                "department=" + department +
                ", roles=" + roles +
                ", newPassword='" + newPassword + '\'' +
                ", employeeDetails='" + employeeDetails + '\'' +
                ", transferCompany=" + transferCompany +
                ", team=" + team +
                ", companyId=" + companyId +
                ", isTeamLeader=" + isTeamLeader +
                ", headImg='" + headImg + '\'' +
                ", id=" + id +
                ", username='" + username + '\'' +
                ", realname='" + realname + '\'' +
                ", password='" + password + '\'' +
                ", tel=" + tel +
                ", email='" + email + '\'' +
                ", inputTime=" + inputTime +
                ", state=" + state +
                '}';
    }

    public String getEmployeeDetails() {
        return employeeDetails;
    }

    public void setEmployeeDetails(String employeeDetails) {
        this.employeeDetails = employeeDetails;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    private TSystemDictionaryItem transferCompany;


    public TSystemDictionaryItem getTransferCompany() {
        return transferCompany;
    }

    public void setTransferCompany(TSystemDictionaryItem transferCompany) {
        this.transferCompany = transferCompany;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    private Long team;
    private Long companyId;
    private Long isTeamLeader;



    public Long getTeam() {
        return team;
    }

    public void setTeam(Long team) {
        this.team = team;
    }

    public Long getIsTeamLeader() {
        return isTeamLeader;
    }

    public void setIsTeamLeader(Long isTeamLeader) {
        this.isTeamLeader = isTeamLeader;
    }

    private String headImg;

    public String getHeadImg() {
        return headImg;
    }

    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.tel
     *
     * @mbggenerated
     */
    private Integer tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.inputTime
     *
     * @mbggenerated
     */
    private Date inputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.username
     *
     * @return the value of employee.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.username
     *
     * @param username the value for employee.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.realname
     *
     * @return the value of employee.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.realname
     *
     * @param realname the value for employee.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.password
     *
     * @return the value of employee.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.password
     *
     * @param password the value for employee.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.tel
     *
     * @return the value of employee.tel
     *
     * @mbggenerated
     */
    public Integer getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.tel
     *
     * @param tel the value for employee.tel
     *
     * @mbggenerated
     */
    public void setTel(Integer tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.email
     *
     * @return the value of employee.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.email
     *
     * @param email the value for employee.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.inputTime
     *
     * @return the value of employee.inputTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.inputTime
     *
     * @param inputTime the value for employee.inputTime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.state
     *
     * @return the value of employee.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.state
     *
     * @param state the value for employee.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    public List<Employee_Role> getEmployee_Roles() {
        List<Employee_Role> list_rp = new ArrayList<>();
        Long id = this.getId();
        List<Role> p = this.getRoles();
        for (Role p2 : p) {
            list_rp.add(new Employee_Role(id, p2.getId()));
        }
        return list_rp;
    }
}