package com.decisioncustom.domain;

public class Role_Permission {
    public Role_Permission(Long roleId, Long permissionId) {
        super();
        this.roleId = roleId;
        this.permissionId = permissionId;
    }
    public Role_Permission() {
        super();
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.roleId
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.permissionId
     *
     * @mbggenerated
     */
    private Long permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.roleId
     *
     * @return the value of role_permission.roleId
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.roleId
     *
     * @param roleId the value for role_permission.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.permissionId
     *
     * @return the value of role_permission.permissionId
     *
     * @mbggenerated
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.permissionId
     *
     * @param permissionId the value for role_permission.permissionId
     *
     * @mbggenerated
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }
}