package com.decisioncustom.domain;

public class TCustomerComplainText {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_complain_text.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_complain_text.complain_reason_detail
     *
     * @mbggenerated
     */
    private String complainReasonDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_complain_text.id
     *
     * @return the value of t_customer_complain_text.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_complain_text.id
     *
     * @param id the value for t_customer_complain_text.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_complain_text.complain_reason_detail
     *
     * @return the value of t_customer_complain_text.complain_reason_detail
     *
     * @mbggenerated
     */
    public String getComplainReasonDetail() {
        return complainReasonDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_complain_text.complain_reason_detail
     *
     * @param complainReasonDetail the value for t_customer_complain_text.complain_reason_detail
     *
     * @mbggenerated
     */
    public void setComplainReasonDetail(String complainReasonDetail) {
        this.complainReasonDetail = complainReasonDetail == null ? null : complainReasonDetail.trim();
    }
}