package com.decisioncustom.domain;

public class TCustomerEmployee {
    public TCustomerEmployee(Long customerId, Long employeeId) {
        super();
        this.customerId = customerId;
        this.employeeId = employeeId;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_employee.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_employee.employee_id
     *
     * @mbggenerated
     */
    private Long employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_employee.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_employee.id
     *
     * @return the value of t_customer_employee.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_employee.id
     *
     * @param id the value for t_customer_employee.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_employee.employee_id
     *
     * @return the value of t_customer_employee.employee_id
     *
     * @mbggenerated
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_employee.employee_id
     *
     * @param employeeId the value for t_customer_employee.employee_id
     *
     * @mbggenerated
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_employee.customer_id
     *
     * @return the value of t_customer_employee.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_employee.customer_id
     *
     * @param customerId the value for t_customer_employee.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
}