package com.decisioncustom.domain;

import java.math.BigDecimal;
import java.util.Date;

public class TCustomerRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_record.stock_id
     *
     * @mbggenerated
     */
    private Long stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_record.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_record.present_price
     *
     * @mbggenerated
     */
    private BigDecimal presentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_record.stock_code
     *
     * @mbggenerated
     */
    private String stockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_record.stock_name
     *
     * @mbggenerated
     */
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_record.transaction_price
     *
     * @mbggenerated
     */
    private BigDecimal transactionPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_record.transaction_num
     *
     * @mbggenerated
     */
    private Long transactionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_record.transaction_amont
     *
     * @mbggenerated
     */
    private BigDecimal transactionAmont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_record.profit_loss_than
     *
     * @mbggenerated
     */
    private BigDecimal profitLossThan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_record.profit_loss_amont
     *
     * @mbggenerated
     */
    private BigDecimal profitLossAmont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_record.operation_date
     *
     * @mbggenerated
     */
    private Date operationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_record.operation_type
     *
     * @mbggenerated
     */
    private Integer operationType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_record.id
     *
     * @return the value of t_customer_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_record.id
     *
     * @param id the value for t_customer_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_record.stock_id
     *
     * @return the value of t_customer_record.stock_id
     *
     * @mbggenerated
     */
    public Long getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_record.stock_id
     *
     * @param stockId the value for t_customer_record.stock_id
     *
     * @mbggenerated
     */
    public void setStockId(Long stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_record.customer_id
     *
     * @return the value of t_customer_record.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_record.customer_id
     *
     * @param customerId the value for t_customer_record.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_record.present_price
     *
     * @return the value of t_customer_record.present_price
     *
     * @mbggenerated
     */
    public BigDecimal getPresentPrice() {
        return presentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_record.present_price
     *
     * @param presentPrice the value for t_customer_record.present_price
     *
     * @mbggenerated
     */
    public void setPresentPrice(BigDecimal presentPrice) {
        this.presentPrice = presentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_record.stock_code
     *
     * @return the value of t_customer_record.stock_code
     *
     * @mbggenerated
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_record.stock_code
     *
     * @param stockCode the value for t_customer_record.stock_code
     *
     * @mbggenerated
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_record.stock_name
     *
     * @return the value of t_customer_record.stock_name
     *
     * @mbggenerated
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_record.stock_name
     *
     * @param stockName the value for t_customer_record.stock_name
     *
     * @mbggenerated
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_record.transaction_price
     *
     * @return the value of t_customer_record.transaction_price
     *
     * @mbggenerated
     */
    public BigDecimal getTransactionPrice() {
        return transactionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_record.transaction_price
     *
     * @param transactionPrice the value for t_customer_record.transaction_price
     *
     * @mbggenerated
     */
    public void setTransactionPrice(BigDecimal transactionPrice) {
        this.transactionPrice = transactionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_record.transaction_num
     *
     * @return the value of t_customer_record.transaction_num
     *
     * @mbggenerated
     */
    public Long getTransactionNum() {
        return transactionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_record.transaction_num
     *
     * @param transactionNum the value for t_customer_record.transaction_num
     *
     * @mbggenerated
     */
    public void setTransactionNum(Long transactionNum) {
        this.transactionNum = transactionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_record.transaction_amont
     *
     * @return the value of t_customer_record.transaction_amont
     *
     * @mbggenerated
     */
    public BigDecimal getTransactionAmont() {
        return transactionAmont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_record.transaction_amont
     *
     * @param transactionAmont the value for t_customer_record.transaction_amont
     *
     * @mbggenerated
     */
    public void setTransactionAmont(BigDecimal transactionAmont) {
        this.transactionAmont = transactionAmont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_record.profit_loss_than
     *
     * @return the value of t_customer_record.profit_loss_than
     *
     * @mbggenerated
     */
    public BigDecimal getProfitLossThan() {
        return profitLossThan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_record.profit_loss_than
     *
     * @param profitLossThan the value for t_customer_record.profit_loss_than
     *
     * @mbggenerated
     */
    public void setProfitLossThan(BigDecimal profitLossThan) {
        this.profitLossThan = profitLossThan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_record.profit_loss_amont
     *
     * @return the value of t_customer_record.profit_loss_amont
     *
     * @mbggenerated
     */
    public BigDecimal getProfitLossAmont() {
        return profitLossAmont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_record.profit_loss_amont
     *
     * @param profitLossAmont the value for t_customer_record.profit_loss_amont
     *
     * @mbggenerated
     */
    public void setProfitLossAmont(BigDecimal profitLossAmont) {
        this.profitLossAmont = profitLossAmont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_record.operation_date
     *
     * @return the value of t_customer_record.operation_date
     *
     * @mbggenerated
     */
    public Date getOperationDate() {
        return operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_record.operation_date
     *
     * @param operationDate the value for t_customer_record.operation_date
     *
     * @mbggenerated
     */
    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_record.operation_type
     *
     * @return the value of t_customer_record.operation_type
     *
     * @mbggenerated
     */
    public Integer getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_record.operation_type
     *
     * @param operationType the value for t_customer_record.operation_type
     *
     * @mbggenerated
     */
    public void setOperationType(Integer operationType) {
        this.operationType = operationType;
    }
}