package com.decisioncustom.domain;

public class TCustomerComplainEmployee {
    public TCustomerComplainEmployee(Long customerComplainId, Long employeeId) {
        super();
        this.customerComplainId = customerComplainId;
        this.employeeId = employeeId;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_complain_employee.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_complain_employee.customer_complain_id
     *
     * @mbggenerated
     */
    private Long customerComplainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_complain_employee.employee_id
     *
     * @mbggenerated
     */
    private Long employeeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_complain_employee.id
     *
     * @return the value of t_customer_complain_employee.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_complain_employee.id
     *
     * @param id the value for t_customer_complain_employee.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_complain_employee.customer_complain_id
     *
     * @return the value of t_customer_complain_employee.customer_complain_id
     *
     * @mbggenerated
     */
    public Long getCustomerComplainId() {
        return customerComplainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_complain_employee.customer_complain_id
     *
     * @param customerComplainId the value for t_customer_complain_employee.customer_complain_id
     *
     * @mbggenerated
     */
    public void setCustomerComplainId(Long customerComplainId) {
        this.customerComplainId = customerComplainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_complain_employee.employee_id
     *
     * @return the value of t_customer_complain_employee.employee_id
     *
     * @mbggenerated
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_complain_employee.employee_id
     *
     * @param employeeId the value for t_customer_complain_employee.employee_id
     *
     * @mbggenerated
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }
}