package com.decisioncustom.domain;

public class TEmployeeRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_role.employeeId
     *
     * @mbggenerated
     */
    private Long employeeId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_role.roleId
     *
     * @mbggenerated
     */
    private Long roleId;

    @Override
    public String toString() {
        return "TEmployeeRole{" +
                "employeeId=" + employeeId +
                ", roleId=" + roleId +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_role.employeeId
     *
     * @return the value of employee_role.employeeId
     *
     * @mbggenerated
     */
    public Long getEmployeeId() {
        return employeeId;
    }
    public TEmployeeRole(Long employeeId, Long roleId) {
        super();
        this.employeeId = employeeId;
        this.roleId = roleId;
    }
    public TEmployeeRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_role.employeeId
     *
     * @param employeeId the value for employee_role.employeeId
     *
     * @mbggenerated
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_role.roleId
     *
     * @return the value of employee_role.roleId
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_role.roleId
     *
     * @param roleId the value for employee_role.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}