package com.decisioncustom.domain;

public class TImgs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_imgs.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_imgs.img_way
     *
     * @mbggenerated
     */
    private String imgWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_imgs.img_type
     *
     * @mbggenerated
     */
    private Long imgType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_imgs.id
     *
     * @return the value of t_imgs.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_imgs.id
     *
     * @param id the value for t_imgs.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_imgs.img_way
     *
     * @return the value of t_imgs.img_way
     *
     * @mbggenerated
     */
    public String getImgWay() {
        return imgWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_imgs.img_way
     *
     * @param imgWay the value for t_imgs.img_way
     *
     * @mbggenerated
     */
    public void setImgWay(String imgWay) {
        this.imgWay = imgWay == null ? null : imgWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_imgs.img_type
     *
     * @return the value of t_imgs.img_type
     *
     * @mbggenerated
     */
    public Long getImgType() {
        return imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_imgs.img_type
     *
     * @param imgType the value for t_imgs.img_type
     *
     * @mbggenerated
     */
    public void setImgType(Long imgType) {
        this.imgType = imgType;
    }
}