package com.decisioncustom.domain;

import java.util.Date;

public class TIntelligenceAgencies {

    private  Employee employee;
    @Override
    public String toString() {
        return "TIntelligenceAgencies{" +
                "id=" + id +
                ", teacherId=" + teacherId +
                ", intelligenceTitle='" + intelligenceTitle + '\'' +
                ", creationTime=" + creationTime +
                ", updateTime=" + updateTime +
                ", imgId=" + imgId +
                ", readingQuantity=" + readingQuantity +
                ", top=" + top +
                ", textId=" + textId +
                '}';
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligence_agencies.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligence_agencies.teacher_id
     *
     * @mbggenerated
     */
    private Long teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligence_agencies.intelligence_title
     *
     * @mbggenerated
     */
    private String intelligenceTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligence_agencies.creation_time
     *
     * @mbggenerated
     */
    private Date creationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligence_agencies.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligence_agencies.img_id
     *
     * @mbggenerated
     */
    private Long imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligence_agencies.reading_quantity
     *
     * @mbggenerated
     */
    private Long readingQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligence_agencies.top
     *
     * @mbggenerated
     */
    private Integer top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_intelligence_agencies.text_id
     *
     * @mbggenerated
     */
    private Long textId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligence_agencies.id
     *
     * @return the value of t_intelligence_agencies.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligence_agencies.id
     *
     * @param id the value for t_intelligence_agencies.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligence_agencies.teacher_id
     *
     * @return the value of t_intelligence_agencies.teacher_id
     *
     * @mbggenerated
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligence_agencies.teacher_id
     *
     * @param teacherId the value for t_intelligence_agencies.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligence_agencies.intelligence_title
     *
     * @return the value of t_intelligence_agencies.intelligence_title
     *
     * @mbggenerated
     */
    public String getIntelligenceTitle() {
        return intelligenceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligence_agencies.intelligence_title
     *
     * @param intelligenceTitle the value for t_intelligence_agencies.intelligence_title
     *
     * @mbggenerated
     */
    public void setIntelligenceTitle(String intelligenceTitle) {
        this.intelligenceTitle = intelligenceTitle == null ? null : intelligenceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligence_agencies.creation_time
     *
     * @return the value of t_intelligence_agencies.creation_time
     *
     * @mbggenerated
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligence_agencies.creation_time
     *
     * @param creationTime the value for t_intelligence_agencies.creation_time
     *
     * @mbggenerated
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligence_agencies.update_time
     *
     * @return the value of t_intelligence_agencies.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligence_agencies.update_time
     *
     * @param updateTime the value for t_intelligence_agencies.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligence_agencies.img_id
     *
     * @return the value of t_intelligence_agencies.img_id
     *
     * @mbggenerated
     */
    public Long getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligence_agencies.img_id
     *
     * @param imgId the value for t_intelligence_agencies.img_id
     *
     * @mbggenerated
     */
    public void setImgId(Long imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligence_agencies.reading_quantity
     *
     * @return the value of t_intelligence_agencies.reading_quantity
     *
     * @mbggenerated
     */
    public Long getReadingQuantity() {
        return readingQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligence_agencies.reading_quantity
     *
     * @param readingQuantity the value for t_intelligence_agencies.reading_quantity
     *
     * @mbggenerated
     */
    public void setReadingQuantity(Long readingQuantity) {
        this.readingQuantity = readingQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligence_agencies.top
     *
     * @return the value of t_intelligence_agencies.top
     *
     * @mbggenerated
     */
    public Integer getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligence_agencies.top
     *
     * @param top the value for t_intelligence_agencies.top
     *
     * @mbggenerated
     */
    public void setTop(Integer top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_intelligence_agencies.text_id
     *
     * @return the value of t_intelligence_agencies.text_id
     *
     * @mbggenerated
     */
    public Long getTextId() {
        return textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_intelligence_agencies.text_id
     *
     * @param textId the value for t_intelligence_agencies.text_id
     *
     * @mbggenerated
     */
    public void setTextId(Long textId) {
        this.textId = textId;
    }
}