package com.decisioncustom.domain;

import java.util.Date;

public class TJiePan {
    private TEmployee adviser;

    public TEmployee getAdviser() {
        return adviser;
    }

    public void setAdviser(TEmployee adviser) {
        this.adviser = adviser;
    }

    @Override
    public String toString() {
        return "TJiePan{" +
                "adviser=" + adviser +
                ", id=" + id +
                ", teacherId=" + teacherId +
                ", text='" + text + '\'' +
                ", date=" + date +
                ", top=" + top +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jie_pan.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jie_pan.teacher_id
     *
     * @mbggenerated
     */
    private Long teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jie_pan.text
     *
     * @mbggenerated
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jie_pan.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jie_pan.top
     *
     * @mbggenerated
     */
    private Integer top;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jie_pan.id
     *
     * @return the value of t_jie_pan.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jie_pan.id
     *
     * @param id the value for t_jie_pan.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jie_pan.teacher_id
     *
     * @return the value of t_jie_pan.teacher_id
     *
     * @mbggenerated
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jie_pan.teacher_id
     *
     * @param teacherId the value for t_jie_pan.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jie_pan.text
     *
     * @return the value of t_jie_pan.text
     *
     * @mbggenerated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jie_pan.text
     *
     * @param text the value for t_jie_pan.text
     *
     * @mbggenerated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jie_pan.date
     *
     * @return the value of t_jie_pan.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jie_pan.date
     *
     * @param date the value for t_jie_pan.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jie_pan.top
     *
     * @return the value of t_jie_pan.top
     *
     * @mbggenerated
     */
    public Integer getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jie_pan.top
     *
     * @param top the value for t_jie_pan.top
     *
     * @mbggenerated
     */
    public void setTop(Integer top) {
        this.top = top;
    }
}