package com.decisioncustom.domain;

import java.math.BigDecimal;

public class TLatestList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_latest_list.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_latest_list.teacher_id
     *
     * @mbggenerated
     */
    private Long teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_latest_list.latest_earnings
     *
     * @mbggenerated
     */
    private BigDecimal latestEarnings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_latest_list.month_rate
     *
     * @mbggenerated
     */
    private BigDecimal monthRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_latest_list.overall_rate
     *
     * @mbggenerated
     */
    private BigDecimal overallRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_latest_list.trace_rate
     *
     * @mbggenerated
     */
    private BigDecimal traceRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_latest_list.month_success_rate
     *
     * @mbggenerated
     */
    private BigDecimal monthSuccessRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_latest_list.overall_success_rate
     *
     * @mbggenerated
     */
    private BigDecimal overallSuccessRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_latest_list.id
     *
     * @return the value of t_latest_list.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_latest_list.id
     *
     * @param id the value for t_latest_list.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_latest_list.teacher_id
     *
     * @return the value of t_latest_list.teacher_id
     *
     * @mbggenerated
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_latest_list.teacher_id
     *
     * @param teacherId the value for t_latest_list.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_latest_list.latest_earnings
     *
     * @return the value of t_latest_list.latest_earnings
     *
     * @mbggenerated
     */
    public BigDecimal getLatestEarnings() {
        return latestEarnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_latest_list.latest_earnings
     *
     * @param latestEarnings the value for t_latest_list.latest_earnings
     *
     * @mbggenerated
     */
    public void setLatestEarnings(BigDecimal latestEarnings) {
        this.latestEarnings = latestEarnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_latest_list.month_rate
     *
     * @return the value of t_latest_list.month_rate
     *
     * @mbggenerated
     */
    public BigDecimal getMonthRate() {
        return monthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_latest_list.month_rate
     *
     * @param monthRate the value for t_latest_list.month_rate
     *
     * @mbggenerated
     */
    public void setMonthRate(BigDecimal monthRate) {
        this.monthRate = monthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_latest_list.overall_rate
     *
     * @return the value of t_latest_list.overall_rate
     *
     * @mbggenerated
     */
    public BigDecimal getOverallRate() {
        return overallRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_latest_list.overall_rate
     *
     * @param overallRate the value for t_latest_list.overall_rate
     *
     * @mbggenerated
     */
    public void setOverallRate(BigDecimal overallRate) {
        this.overallRate = overallRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_latest_list.trace_rate
     *
     * @return the value of t_latest_list.trace_rate
     *
     * @mbggenerated
     */
    public BigDecimal getTraceRate() {
        return traceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_latest_list.trace_rate
     *
     * @param traceRate the value for t_latest_list.trace_rate
     *
     * @mbggenerated
     */
    public void setTraceRate(BigDecimal traceRate) {
        this.traceRate = traceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_latest_list.month_success_rate
     *
     * @return the value of t_latest_list.month_success_rate
     *
     * @mbggenerated
     */
    public BigDecimal getMonthSuccessRate() {
        return monthSuccessRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_latest_list.month_success_rate
     *
     * @param monthSuccessRate the value for t_latest_list.month_success_rate
     *
     * @mbggenerated
     */
    public void setMonthSuccessRate(BigDecimal monthSuccessRate) {
        this.monthSuccessRate = monthSuccessRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_latest_list.overall_success_rate
     *
     * @return the value of t_latest_list.overall_success_rate
     *
     * @mbggenerated
     */
    public BigDecimal getOverallSuccessRate() {
        return overallSuccessRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_latest_list.overall_success_rate
     *
     * @param overallSuccessRate the value for t_latest_list.overall_success_rate
     *
     * @mbggenerated
     */
    public void setOverallSuccessRate(BigDecimal overallSuccessRate) {
        this.overallSuccessRate = overallSuccessRate;
    }
}