package com.decisioncustom.domain;

public class TOperatingRecordEmployee {

    public TOperatingRecordEmployee(Long operatingRecordId, Long employeeId) {
        super();
        this.operatingRecordId = operatingRecordId;
        this.employeeId = employeeId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_record_employee.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_record_employee.operating_record_id
     *
     * @mbggenerated
     */
    private Long operatingRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_record_employee.employee_id
     *
     * @mbggenerated
     */
    private Long employeeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_record_employee.id
     *
     * @return the value of t_operating_record_employee.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_record_employee.id
     *
     * @param id the value for t_operating_record_employee.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_record_employee.operating_record_id
     *
     * @return the value of t_operating_record_employee.operating_record_id
     *
     * @mbggenerated
     */
    public Long getOperatingRecordId() {
        return operatingRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_record_employee.operating_record_id
     *
     * @param operatingRecordId the value for t_operating_record_employee.operating_record_id
     *
     * @mbggenerated
     */
    public void setOperatingRecordId(Long operatingRecordId) {
        this.operatingRecordId = operatingRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_record_employee.employee_id
     *
     * @return the value of t_operating_record_employee.employee_id
     *
     * @mbggenerated
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_record_employee.employee_id
     *
     * @param employeeId the value for t_operating_record_employee.employee_id
     *
     * @mbggenerated
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }
}