package com.decisioncustom.domain;

import java.math.BigDecimal;
import java.util.Date;

public class TOperatingData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_data.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_data.stock_name
     *
     * @mbggenerated
     */
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_data.stock_code
     *
     * @mbggenerated
     */
    private String stockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_data.latest_price
     *
     * @mbggenerated
     */
    private BigDecimal latestPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_data.latest_earnings
     *
     * @mbggenerated
     */
    private BigDecimal latestEarnings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_data.buying_price
     *
     * @mbggenerated
     */
    private BigDecimal buyingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_data.buying_time
     *
     * @mbggenerated
     */
    private Date buyingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_data.sell_time
     *
     * @mbggenerated
     */
    private Date sellTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_data.sell_price
     *
     * @mbggenerated
     */
    private BigDecimal sellPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_data.stop_loss_advice
     *
     * @mbggenerated
     */
    private BigDecimal stopLossAdvice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_data.positions_advice
     *
     * @mbggenerated
     */
    private BigDecimal positionsAdvice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operating_data.risk_warning
     *
     * @mbggenerated
     */
    private Integer riskWarning;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_data.id
     *
     * @return the value of t_operating_data.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_data.id
     *
     * @param id the value for t_operating_data.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_data.stock_name
     *
     * @return the value of t_operating_data.stock_name
     *
     * @mbggenerated
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_data.stock_name
     *
     * @param stockName the value for t_operating_data.stock_name
     *
     * @mbggenerated
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_data.stock_code
     *
     * @return the value of t_operating_data.stock_code
     *
     * @mbggenerated
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_data.stock_code
     *
     * @param stockCode the value for t_operating_data.stock_code
     *
     * @mbggenerated
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_data.latest_price
     *
     * @return the value of t_operating_data.latest_price
     *
     * @mbggenerated
     */
    public BigDecimal getLatestPrice() {
        return latestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_data.latest_price
     *
     * @param latestPrice the value for t_operating_data.latest_price
     *
     * @mbggenerated
     */
    public void setLatestPrice(BigDecimal latestPrice) {
        this.latestPrice = latestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_data.latest_earnings
     *
     * @return the value of t_operating_data.latest_earnings
     *
     * @mbggenerated
     */
    public BigDecimal getLatestEarnings() {
        return latestEarnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_data.latest_earnings
     *
     * @param latestEarnings the value for t_operating_data.latest_earnings
     *
     * @mbggenerated
     */
    public void setLatestEarnings(BigDecimal latestEarnings) {
        this.latestEarnings = latestEarnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_data.buying_price
     *
     * @return the value of t_operating_data.buying_price
     *
     * @mbggenerated
     */
    public BigDecimal getBuyingPrice() {
        return buyingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_data.buying_price
     *
     * @param buyingPrice the value for t_operating_data.buying_price
     *
     * @mbggenerated
     */
    public void setBuyingPrice(BigDecimal buyingPrice) {
        this.buyingPrice = buyingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_data.buying_time
     *
     * @return the value of t_operating_data.buying_time
     *
     * @mbggenerated
     */
    public Date getBuyingTime() {
        return buyingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_data.buying_time
     *
     * @param buyingTime the value for t_operating_data.buying_time
     *
     * @mbggenerated
     */
    public void setBuyingTime(Date buyingTime) {
        this.buyingTime = buyingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_data.sell_time
     *
     * @return the value of t_operating_data.sell_time
     *
     * @mbggenerated
     */
    public Date getSellTime() {
        return sellTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_data.sell_time
     *
     * @param sellTime the value for t_operating_data.sell_time
     *
     * @mbggenerated
     */
    public void setSellTime(Date sellTime) {
        this.sellTime = sellTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_data.sell_price
     *
     * @return the value of t_operating_data.sell_price
     *
     * @mbggenerated
     */
    public BigDecimal getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_data.sell_price
     *
     * @param sellPrice the value for t_operating_data.sell_price
     *
     * @mbggenerated
     */
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_data.stop_loss_advice
     *
     * @return the value of t_operating_data.stop_loss_advice
     *
     * @mbggenerated
     */
    public BigDecimal getStopLossAdvice() {
        return stopLossAdvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_data.stop_loss_advice
     *
     * @param stopLossAdvice the value for t_operating_data.stop_loss_advice
     *
     * @mbggenerated
     */
    public void setStopLossAdvice(BigDecimal stopLossAdvice) {
        this.stopLossAdvice = stopLossAdvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_data.positions_advice
     *
     * @return the value of t_operating_data.positions_advice
     *
     * @mbggenerated
     */
    public BigDecimal getPositionsAdvice() {
        return positionsAdvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_data.positions_advice
     *
     * @param positionsAdvice the value for t_operating_data.positions_advice
     *
     * @mbggenerated
     */
    public void setPositionsAdvice(BigDecimal positionsAdvice) {
        this.positionsAdvice = positionsAdvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operating_data.risk_warning
     *
     * @return the value of t_operating_data.risk_warning
     *
     * @mbggenerated
     */
    public Integer getRiskWarning() {
        return riskWarning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operating_data.risk_warning
     *
     * @param riskWarning the value for t_operating_data.risk_warning
     *
     * @mbggenerated
     */
    public void setRiskWarning(Integer riskWarning) {
        this.riskWarning = riskWarning;
    }
}