package com.decisioncustom.domain;

import java.util.Date;

public class TResearchResult {

    private  Employee employee;
    @Override
    public String toString() {
        return "TResearchResult{" +
                "id=" + id +
                ", teacherId=" + teacherId +
                ", imgId=" + imgId +
                ", resultTitle='" + resultTitle + '\'' +
                ", creationTime=" + creationTime +
                ", updateTime=" + updateTime +
                ", original=" + original +
                ", readingQuantity=" + readingQuantity +
                ", textId=" + textId +
                '}';
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_research_result.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_research_result.teacher_id
     *
     * @mbggenerated
     */
    private Long teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_research_result.img_id
     *
     * @mbggenerated
     */
    private Long imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_research_result.result_title
     *
     * @mbggenerated
     */
    private String resultTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_research_result.creation_time
     *
     * @mbggenerated
     */
    private Date creationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_research_result.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_research_result.original
     *
     * @mbggenerated
     */
    private Integer original;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_research_result.reading_quantity
     *
     * @mbggenerated
     */
    private Long readingQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_research_result.text_id
     *
     * @mbggenerated
     */
    private Long textId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_research_result.id
     *
     * @return the value of t_research_result.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_research_result.id
     *
     * @param id the value for t_research_result.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_research_result.teacher_id
     *
     * @return the value of t_research_result.teacher_id
     *
     * @mbggenerated
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_research_result.teacher_id
     *
     * @param teacherId the value for t_research_result.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_research_result.img_id
     *
     * @return the value of t_research_result.img_id
     *
     * @mbggenerated
     */
    public Long getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_research_result.img_id
     *
     * @param imgId the value for t_research_result.img_id
     *
     * @mbggenerated
     */
    public void setImgId(Long imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_research_result.result_title
     *
     * @return the value of t_research_result.result_title
     *
     * @mbggenerated
     */
    public String getResultTitle() {
        return resultTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_research_result.result_title
     *
     * @param resultTitle the value for t_research_result.result_title
     *
     * @mbggenerated
     */
    public void setResultTitle(String resultTitle) {
        this.resultTitle = resultTitle == null ? null : resultTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_research_result.creation_time
     *
     * @return the value of t_research_result.creation_time
     *
     * @mbggenerated
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_research_result.creation_time
     *
     * @param creationTime the value for t_research_result.creation_time
     *
     * @mbggenerated
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_research_result.update_time
     *
     * @return the value of t_research_result.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_research_result.update_time
     *
     * @param updateTime the value for t_research_result.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_research_result.original
     *
     * @return the value of t_research_result.original
     *
     * @mbggenerated
     */
    public Integer getOriginal() {
        return original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_research_result.original
     *
     * @param original the value for t_research_result.original
     *
     * @mbggenerated
     */
    public void setOriginal(Integer original) {
        this.original = original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_research_result.reading_quantity
     *
     * @return the value of t_research_result.reading_quantity
     *
     * @mbggenerated
     */
    public Long getReadingQuantity() {
        return readingQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_research_result.reading_quantity
     *
     * @param readingQuantity the value for t_research_result.reading_quantity
     *
     * @mbggenerated
     */
    public void setReadingQuantity(Long readingQuantity) {
        this.readingQuantity = readingQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_research_result.text_id
     *
     * @return the value of t_research_result.text_id
     *
     * @mbggenerated
     */
    public Long getTextId() {
        return textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_research_result.text_id
     *
     * @param textId the value for t_research_result.text_id
     *
     * @mbggenerated
     */
    public void setTextId(Long textId) {
        this.textId = textId;
    }
}