package com.decisioncustom.domain;

public class TSystemDictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_dictionary.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_dictionary.sn
     *
     * @mbggenerated
     */
    private Integer sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_dictionary.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_dictionary.intro
     *
     * @mbggenerated
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_dictionary.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_dictionary.id
     *
     * @return the value of t_system_dictionary.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_dictionary.id
     *
     * @param id the value for t_system_dictionary.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_dictionary.sn
     *
     * @return the value of t_system_dictionary.sn
     *
     * @mbggenerated
     */
    public Integer getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_dictionary.sn
     *
     * @param sn the value for t_system_dictionary.sn
     *
     * @mbggenerated
     */
    public void setSn(Integer sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_dictionary.name
     *
     * @return the value of t_system_dictionary.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_dictionary.name
     *
     * @param name the value for t_system_dictionary.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_dictionary.intro
     *
     * @return the value of t_system_dictionary.intro
     *
     * @mbggenerated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_dictionary.intro
     *
     * @param intro the value for t_system_dictionary.intro
     *
     * @mbggenerated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_dictionary.state
     *
     * @return the value of t_system_dictionary.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_dictionary.state
     *
     * @param state the value for t_system_dictionary.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}