package com.decisioncustom.domain;

public class TUserTeacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_teacher.user_teacher_id
     *
     * @mbggenerated
     */
    private Long userTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_teacher.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_teacher.teacher_id
     *
     * @mbggenerated
     */
    private Long teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_teacher.user_teacher_id
     *
     * @return the value of t_user_teacher.user_teacher_id
     *
     * @mbggenerated
     */
    public Long getUserTeacherId() {
        return userTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_teacher.user_teacher_id
     *
     * @param userTeacherId the value for t_user_teacher.user_teacher_id
     *
     * @mbggenerated
     */
    public void setUserTeacherId(Long userTeacherId) {
        this.userTeacherId = userTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_teacher.user_id
     *
     * @return the value of t_user_teacher.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_teacher.user_id
     *
     * @param userId the value for t_user_teacher.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_teacher.teacher_id
     *
     * @return the value of t_user_teacher.teacher_id
     *
     * @mbggenerated
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_teacher.teacher_id
     *
     * @param teacherId the value for t_user_teacher.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }
}